---
- name: Update AHV VM HA configuration
  uri:
    url: "https://{{nutanix_host}}:{{nutanix_port}}/PrismGateway/services/rest/v2.0/ha"
    method: PUT
    validate_certs: "{{ validate_certs }}"
    body: "{{ lookup('template', 'ha.j2') | from_yaml | to_json }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ nutanix_api_auth }}"
    return_content: yes
  register: nutanix_prism_ha_update_task
  changed_when: true

- name: Debug nutanix_prism_ha_update_task
  debug:
    var: nutanix_prism_ha_update_task
  when:
    - nutanix_debug

- name: Wait for AHV VM HA configuration task to complete
  block:
    - name: Checking AHV VM HA configuration task status
      uri:
        url: "https://{{nutanix_host}}:{{nutanix_port}}/PrismGateway/services/rest/v2.0/tasks/{{ nutanix_prism_ha_update_task.json.task_uuid }}"
        method: GET
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        headers:
          Authorization: "{{ nutanix_api_auth }}"
      register: prism_ha_update_task_status
      until: prism_ha_update_task_status.json.progress_status == 'Succeeded' or prism_ha_update_task_status.json.progress_status == 'Failed'
      retries: 10
      delay: 30

- name: Checking AHV VM HA configuration task failed
  ansible.builtin.fail:
    msg: "AHV HA update task failed. {{ prism_ha_update_task_status.json.meta_response.error_detail }}"
  when:
    - prism_ha_update_task_status.json.progress_status == 'Failed'
